[build]
  publish = "site"
  functions = "netlify/functions"
  command = "npm run build"

[[redirects]]
  from = "/api/search-books"
  to = "/.netlify/functions/search-books"
  status = 200

[[redirects]]
  from = "/api/holidays"
  to = "/.netlify/functions/holidays"
  status = 200

[[redirects]]
  from = "/api/image-proxy"
  to = "/.netlify/functions/image-proxy"
  status = 200

[[redirects]]
  from = "/api/calendar-state"
  to = "/.netlify/functions/calendar-state"
  status = 200
